version: "3.7"
services:
  postgres_db:
    image: postgres:latest
    container_name: gostack
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gobarber
    ports:
      - "5432:5432"
